language: haskell
install:

  # Install latest cabal to build in parallel
  - time travis/fast-install-cabal
  
  # Prepare logs
  - time travis/touch-logs
  
  # Install some deps with apt-get
  - time sudo apt-get install -q -y libghc-vector-dev libghc-text-dev libghc-bifunctors-dev libghc-blaze-builder-dev libghc-comonad-dev libghc-primitive-dev

  # Install patched packages
  - time travis/install-patched

  # Install dependencies
  - time travis_retry echo $CABAL_FLAGS | xargs $CABAL install --only-dependencies --enable-tests

script: 

  - $CABAL configure --enable-tests && time $CABAL build 

  # Could also use cabal test, but that doesn't provide colorful output
  - dist/build/vplan-tests/vplan-tests --quickcheck-tests 500

env:

  - CABAL=~/.cabal/bin/cabal CABAL_FLAGS='-j --avoid-reinstalls --constraint "text installed" --constraint "vector installed" --constraint "comonad installed" --constraint "primitive installed"'
   