language: haskell
env: PATH = "~/.cabal/bin:$PATH"
before_install:
  - cabal update
  - cabal install cabal-install-1.16.0.2
  - cabal --version
install:
  - ~/.cabal/bin/cabal install --only-dependencies --enable-tests -j