language: haskell
before_install:

  # Install tasty from git, with fixed stm dependency bound and more quickcheck options.
  - git clone -b quickcheck-options https://github.com/bennofs/tasty 
  - cd $TRAVIS_BUILD_DIR/tasty/core       && cabal install
  - cd $TRAVIS_BUILD_DIR/tasty/quickcheck && cabal install

haskell: 7.6
install:

  # Get to the build directory
  - cd $TRAVIS_BUILD_DIR

  # Try installing some of the build-deps with apt-get for speed.
  - travis/cabal-apt-install