language: haskell
install:

  # Install latest cabal to build in parallel
  - time travis/fast-install-cabal
  
  # Prepare logs
  - time travis/touch-logs
  
  # Install some deps with apt-get
  - time sudo apt-get install -q -y libghc-vector-dev libghc-text-dev libghc-aeson-dev libghc-bifunctors-dev libghc-blaze-builder-dev libghc-comonad-dev libghc-comonad-transformers-dev libghc-comonads-fd-dev libghc-contravariant-dev libghc-distributive-dev libghc-dlist-dev libghc-monadcatchio-transformers-dev libghc-primitive-dev libghc-semigroupoids-dev libghc-semigroups-dev libghc-tagged-dev libghc-vector-dev libghc-void-dev

  # Install patched packages
  - time travis/install-patched

  # Install dependencies
  - time travis_retry $CABAL install --only-dependencies --enable-tests $CABAL_FLAGS

script: 

  - $CABAL configure --enable-tests && time $CABAL build 

  # Could also use cabal test, but that doesn't provide colorful output
  - dist/build/vplan-tests/vplan-tests --quickcheck-tests 500

env:

  - CABAL=~/.cabal/bin/cabal CABAL_FLAGS="-j --avoid-reinstalls --enable-tests --constraint \"text installed\" --constraint \"vector installed\" --constraint \"void installed\" --constraint \"contravariant installed\" --constraint \"distributive installed\" --constraint \"comonads installed\" --constraint \"comonads-fd installed\" --constraint \"comonad-transformers installed\""
                
   