language: haskell
install:

  # Install latest cabal to build in parallel
  - time travis/fast-install-cabal
  
  # Prepare logs
  - time travis/touch-logs
  
  # Install some deps with apt-get
  - time sudo apt-get install -q -y libghc-vector-dev libghc-aeson-dev libghc-text-dev

  # Install patched packages
  - time travis/install-patched

  # Install dependencies
  - time travis_retry $CABAL install --only-dependencies --enable-tests $CABAL_FLAGS

script: 

  # Could also use cabal test, but that doesn't provide colorful output
  - time $CABAL configure --enable-tests && $CABAL build && dist/build/vplan-tests/vplan-tests --quickcheck-tests 500

env:

  - CABAL=~/.cabal/bin/cabal 
    CABAL_FLAGS=-j --avoid-reinstalls --enable-tests --constraint "text installed" --constraint "vector installed"