language: haskell
before_install:

  # Install tasty from git, with fixed stm dependency bound and more quickcheck options.
  - git clone -b quickcheck-options https://github.com/bennofs/tasty 
  - pushd && cd tasty/core && cabal install && popd
  - pushd && cd tasty/quickcheck && cabal install && popd
  - echo $PWD # Test

install:

  # Try installing some of the build-deps with apt-get for speed.
   - travis/cabal-apt-install