#! /bin/bash
set -eu

APT="sudo apt-get -q -y"
CABAL_INSTALL_DEPS="$CABAL install --only-dependencies $CABAL_FLAGS"

$APT update
$APT install dctrl-tools

# Find potential system packages to satisfy cabal dependencies
deps()
{
  local M='^([^ ]+)-[0-9.]+.*$'
  echo $M
  local G=' -o ( -P -X libghc-\L\1\E-dev )'
  echo $G
  local E="$($CABAL_INSTALL_DEPS "$@" --dry-run -v 2> /dev/null \
  | tail -n+3 | sed -re "s/$M/$G/p" | sort -u)"
  echo $E
  grep-aptavail -n -sPackage \( -FNone -X None \) $E | sort -u
}

$APT install $(deps "$@") libghc-quickcheck2-dev # QuickCheck is special

if ! $APT install hlint ; then
$APT install $(deps hlint)
$CABAL install hlint $CABAL_FLAGS
fi
