#!/bin/sh

# This script downloads and installs GHC 7.6.2 (Travis has only 7.4, which is too old for this app)

# Prepare
sudo apt-get install libgmp3

# Download and unpack
wget http://www.haskell.org/ghc/dist/7.6.2/ghc-7.6.2-x86_64-unknown-linux.tar.bz2
tar -xf ghc-7.6.2-x86_64-unknown-linux.tar.bz2
cd ghc-7.6.2

# Install
./configure
sudo make install
